#!/bin/sh

# Hooks into __sm.package.gnu.install() parent function in SM's core/internal/package/functions

roundup_fetch()
{
  fetch_uri "https://github.com/bmizerany/roundup/tarball/master" "${source_path}/${package_dir}"
}

roundup_extract()
{
  true
}

roundup_configure()
{
  cd ${source_path}
  ./configure --prefix=${install_path}
}

roundup_build()
{
  make
}

roundup_install()
{
  make install
}

